[project]
name = "licensed-sponsor-swv-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "fastmcp>=2.10.1",
    "pandas>=2.3.0",
    "rapidfuzz>=3.13.0",
    "requests>=2.32.4",
]
